server:
  port: 8080   # Puerto único del Gateway

spring:
  cloud:
    gateway:
      routes:
        # Ruta hacia el microservicio de usuarios
        - id: usuarios-service
          uri: http://localhost:8081   # Puerto donde corre tu microservicio de usuarios
          predicates:
            - Path=/api/usuarios/**

        # Ruta hacia el microservicio de autenticación
        - id: auth-service
          uri: http://localhost:8082   # Puerto donde corre tu microservicio de auth
          predicates:
            - Path=/api/auth/**

        # Ruta hacia el microservicio de formularios
        - id: formulario-service
          uri: http://localhost:8083   # Puerto donde corre tu microservicio de formularios
          predicates:
            - Path=/formularios/**
